export { Header as ComponentHeader } from "./Header"
export { Footer as ComponentFooter } from "./Footer"
export { Card as ComponentCard } from "./Card"
export { Superdecolar as Componentdecolar} from "./Superdecolar"
export {BemVindo as ComponentBemVindo} from "./Bemvindo"
